name: Publish TekaTeka

on:
  push:
    tags: "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Download Dependencies
        env:
          GAME_DEPENDENCIES_URL: ${{ secrets.GAME_DEPENDENCIES_URL }}
        run: |
          wget -O dependencies.zip $GAME_DEPENDENCIES_URL -nv
          unzip dependencies.zip -d dependencies

      - name: Setup Project
        run: |
          dotnet nuget add source https://nuget.bepinex.dev/v3/index.json
          dotnet nuget add source https://nuget.samboy.dev/v3/index.json
          dotnet restore TekaTeka.sln

      - name: Build Release
        run: |
          dotnet build "/p:GameDir=$(realpath ./dependencies/);WORKER=GitHub" --configuration Release TekaTeka.sln

      - name: Pack Release
        run: |
          mkdir release
          mkdir ./release/RF.TekaTeka
          cp ./Libraries/SonicAudioLib.dll ./release/RF.TekaTeka/SonicAudioLib.dll
          cp ./TekaTeka/bin/Release/net6.0/RF.TekaTeka.dll ./release/RF.TekaTeka/RF.TekaTeka.dll
          cp ./TekaTeka/bin/Release/net6.0/RF.TekaTeka.pdb ./release/RF.TekaTeka.pdb
          cd ./release
          zip ./RF.TekaTeka.zip ./RF.TekaTeka/RF.TekaTeka.dll ./RF.TekaTeka/SonicAudioLib.dll

      - name: Create Release Page
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          body: |
            ## How to use

            - Install [BepInEx](https://docs.bepinex.dev/articles/user_guide/installation/index.html)
            - Download the latest version of `RF.TekaTeka.zip` from this page and extract its contents on `(GameFolder)\BepInEx\plugins\`
            - Place all your mods on the folder named `TekaSongs` created the first time you execute the mod

            ## CHANGELOG
              
            `TODO`
          files: |
            ./release/RF.TekaTeka.zip
            ./TekaTeka/bin/Release/net6.0/RF.TekaTeka.pdb
